// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  custom_ring: dynamic(() => import("./CustomRing")),
  hero: dynamic(() => import("./Hero")),
};
